== DropwizardMetricsOptions

++++
 Vert.x Dropwizard metrics configuration.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description

|[[registryName]]`registryName`
|`String`
|+++
Set the name used for registering the metrics in the Dropwizard shared registry.+++

|[[jmxEnabled]]`jmxEnabled`
|`Boolean`
|+++
Set whether JMX will be enabled on the Vert.x instance.+++

|[[jmxDomain]]`jmxDomain`
|`String`
|+++
Set the JMX domain to use when JMX metrics are enabled.+++

|[[monitoredEventBusHandlers]]`monitoredEventBusHandlers`
|`Array of link:Match.html[Match]`
|+++
Add a monitored event bus handler.+++

|[[monitoredHttpServerUris]]`monitoredHttpServerUris`
|`Array of link:Match.html[Match]`
|+++
Add an monitored http server uri.+++

|[[enabled]]`enabled`
|`Boolean`
|-
|[[configPath]]`configPath`
|`String`
|+++
Set the file name for a config file that contains options in JSON format, to be used to create a new options object.
 The file will be looked for on the file system first and then on the classpath if it's not found.+++

|[[monitoredHttpClientUris]]`monitoredHttpClientUris`
|`Array of link:Match.html[Match]`
|+++
Add an monitored http client uri.+++
|===
