= Metrics

Vert.x provides a Service Provider Interface for reporting metrics to implementations of this SPI.

This project
is an implementation of the Vert.x SPI that uses Dropwizard metrics](https://github.com/dropwizard/metrics) library.

This library is then used for obtaining measurements snapshots and reporting to thirdparty collectors such as JMX.


Vert.x metrics provides a fairly simple API to retrieve metrics via the `link:groovydoc/io/vertx/groovy/core/metrics/Measured.html[Measured]`
interface which is implemented by various Vert.x components like `link:groovydoc/io/vertx/groovy/core/http/HttpServer.html[HttpServer]`,
`link:groovydoc/io/vertx/groovy/core/net/NetServer.html[NetServer]`, and even `link:groovydoc/io/vertx/groovy/core/Vertx.html[Vertx]` itself.

By default Vert.x does not record any metrics. Instead it provides an SPI for others to implement which can be added
to the classpath. Once added, you can enable metrics by doing the following:

[source,groovy]
----
import io.vertx.groovy.core.Vertx
def vertx = Vertx.vertx([
  metricsOptions:[
    enabled:true
  ]
])

----

Once enabled, you can retrieve metrics from any `link:groovydoc/io/vertx/groovy/core/metrics/Measured.html[Measured]` object which provides
a map of the metric name to the data, represented by a `link:groovydoc/io/vertx/groovy/core/json/JsonObject.html[JsonObject]`. So for example if we
were to print out all metrics for a particular Vert.x instance:
[source,groovy]
----
import io.vertx.groovy.ext.metrics.MetricsService
def metricsService = MetricsService.create(vertx)
def metrics = metricsService.getMetricsSnapshot(vertx)
metrics.each { name, metric ->
  println("${name} : ${metric.toString()}")
}

----

NOTE: For details on the actual contents of the data (the actual metric) represented by the `link:groovydoc/io/vertx/groovy/core/json/JsonObject.html[JsonObject]`
consult the implementation documentation like https://github.com/vert-x3/vertx-metrics[vertx-metrics]

Often it is desired that you only want to capture specific metrics for a particular component, like an http server
without having to know the details of the naming scheme of every metric (something which is left to the implementers of the SPI).

Since `link:groovydoc/io/vertx/groovy/core/http/HttpServer.html[HttpServer]` implements `link:groovydoc/io/vertx/groovy/core/metrics/Measured.html[Measured]`, you can easily grab all metrics
that are specific for that particular http server.
[source,groovy]
----
import io.vertx.groovy.ext.metrics.MetricsService
def metricsService = MetricsService.create(vertx)
def server = vertx.createHttpServer()
// set up server
def metrics = metricsService.getMetricsSnapshot(server)

----