= Metrics

This project implements the Vert.x Metrics Service Provider Interface (SPI) reporting metrics to the
[Dropwizard metrics](https://github.com/dropwizard/metrics) library.

== Features

A fairly simple API to retrieve metrics via the `link:groovydoc/io/vertx/groovy/core/metrics/Measured.html[Measured]`
interface which is implemented by various Vert.x components like `link:groovydoc/io/vertx/groovy/core/http/HttpServer.html[HttpServer]`,
`link:groovydoc/io/vertx/groovy/core/net/NetServer.html[NetServer]`, and even `link:groovydoc/io/vertx/groovy/core/Vertx.html[Vertx]` itself.

Confiugrable JMX reporting based on Dropwizard implementation, exposing Vert.x as JMX MBeans.

== Getting started

To enable metrics first setup maven to include this as a dependency

----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>ext-metrics</artifactId>
  <version>${vertx.metrics.version}</version>
</dependency>
----

Then when you create vertx enable metrics using the `link:../cheatsheet/MetricsServiceOptions.html[MetricsServiceOptions]`:

[source,groovy]
----
import io.vertx.groovy.core.Vertx
def vertx = Vertx.vertx([
  metricsOptions:[
    enabled:true
  ]
])

----

You can also enable JMX:

[source,groovy]
----
import io.vertx.groovy.core.Vertx
def vertx = Vertx.vertx([
  metricsOptions:[
    enabled:true,
    jmxEnabled:true
  ]
])

----

To see details about JMX see the <<jmx>> section at the bottom.

== Metrics service

== Naming

Each measured component listed below (except for Vertx) will have a base name associated with it. Each metric
can be retrieved by providing the fully qualified name <fqn> `baseName` + `.` + `metricName` from Vertx:

[source,groovy]
----
def metrics = metricsService.getMetricsSnapshot(vertx)
metrics["vertx.eventbus.handlers"]

----

or from the measured component itself using just the metric name:

[source,groovy]
----
def eventBus = vertx.eventBus()
def metrics = metricsService.getMetricsSnapshot(eventBus)
metrics["handlers"]

----

See more examples below on how to retrieve/use metrics for a specific component.

== Retrieving metrics

Once enabled, the `link:groovydoc/io/vertx/groovy/ext/metrics/MetricsService.html[MetricsService]` allows to retrieve metrics snapshots from any
`link:groovydoc/io/vertx/groovy/core/metrics/Measured.html[Measured]` object which provides a map of the metric name to the data,
represented by a `link:groovydoc/io/vertx/groovy/core/json/JsonObject.html[JsonObject]`. So for example if we were to print out all metrics
for a particular Vert.x instance:
[source,groovy]
----
import io.vertx.groovy.ext.metrics.MetricsService
def metricsService = MetricsService.create(vertx)
def metrics = metricsService.getMetricsSnapshot(vertx)
metrics.each { name, metric ->
  println("${name} : ${metric.toString()}")
}

----

NOTE: For details on the actual contents of the data (the actual metric) represented by the `link:groovydoc/io/vertx/groovy/core/json/JsonObject.html[JsonObject]`
consult the implementation documentation like https://github.com/vert-x3/vertx-metrics[vertx-metrics]

Often it is desired that you only want to capture specific metrics for a particular component, like an http server
without having to know the details of the naming scheme of every metric (something which is left to the implementers of the SPI).

Since `link:groovydoc/io/vertx/groovy/core/http/HttpServer.html[HttpServer]` implements `link:groovydoc/io/vertx/groovy/core/metrics/Measured.html[Measured]`, you can easily grab all metrics
that are specific for that particular http server.
[source,groovy]
----
import io.vertx.groovy.ext.metrics.MetricsService
def metricsService = MetricsService.create(vertx)
def server = vertx.createHttpServer()
// set up server
def metrics = metricsService.getMetricsSnapshot(server)

----

== Data

Below is how each dropwizard metric is represented in JSON. Please refer to the
[Dropwizard metrics](https://github.com/dropwizard/metrics) documentation for detailed information on each metric.

=== Gauge

[source,javascript]
----
{
  "value" : value // any json value
}
----

=== Counter

[source,groovy]
----
{
  "count" : 1 // number
}
----

=== Histogram

[source,javascript]
----
{
  "count"  : 1 // long
  "min"    : 1 // long
  "max"    : 1 // long
  "mean"   : 1.0 // double
  "stddev" : 1.0 // double
  "median" : 1.0 // double
  "75%"    : 1.0 // double
  "95%"    : 1.0 // double
  "98%"    : 1.0 // double
  "99%"    : 1.0 // double
  "99.9%"  : 1.0 // double
}
----

=== Meter

[source,groovy]
----
{
  "count"             : 1 // long
  "meanRate"          : 1.0 // double
  "oneMinuteRate"     : 1.0 // double
  "fiveMinuteRate"    : 1.0 // double
  "fifteenMinuteRate" : 1.0 // double
  "rate"              : "events/second" // string representing rate
}
----

=== Timer

A timer is basically a combination of Histogram + Meter.

[source,groovy]
----
{
  // histogram data
  "count"  : 1 // long
  "min"    : 1 // long
  "max"    : 1 // long
  "mean"   : 1.0 // double
  "stddev" : 1.0 // double
  "median" : 1.0 // double
  "75%"    : 1.0 // double
  "95%"    : 1.0 // double
  "98%"    : 1.0 // double
  "99%"    : 1.0 // double
  "99.9%"  : 1.0 // double

  // meter data
  "meanRate"          : 1.0 // double
  "oneMinuteRate"     : 1.0 // double
  "fiveMinuteRate"    : 1.0 // double
  "fifteenMinuteRate" : 1.0 // double
  "rate"              : "events/second" // string representing rate
}
----

== The metrics

The following metrics are currently provided.

=== Vert.x metrics

The following metrics are provided:

* `vertx.event-loop-size` - A [Gauge](#gauge) of the number of threads in the event loop pool
* `vertx.worker-pool-size` - A [Gauge](#gauge) of the number of threads in the worker pool
* `vertx.cluster-host` - A [Gauge](#gauge) of the cluster-host setting
* `vertx.cluster-port` - A [Gauge](#gauge) of the cluster-port setting
* `vertx.verticles` - A [Counter](#counter) of the number of verticles currently deployed

=== Event bus metrics

Base name: `vertx.eventbus`

* `handlers` - A [Counter](#counter) of the number of event bus handlers
* `messages.received` - A [Meter](#meter) representing the rate of which messages are being received
* `messages.sent` - A [Meter](#meter) representing the rate of which messages are being sent
* `messages.published` - A [Meter](#meter) representing the rate of which messages are being published
* `messages.reply-failures` - A [Meter](#meter) representing the rate of reply failures

=== Http server metrics

Base name: `vertx.http.servers.<host>:<port>`

Http server includes all the metrics of a [Net Server](#net-server-metrics)* plus the following:

* `requests` - A [Timer](#timer) of a request and the rate of it's occurrence
* `<http-method>-requests` - A [Timer](#timer) of a specific http method request and the rate of it's occurrence
** Examples: `get-requests`, `post-requests`
* `<http-method>-requests./<uri>` - A [Timer](#timer) of a specific http method & URI request and the rate of it's occurrence
** Examples: `get-requests./some/uri`, `post-requests./some/uri?foo=bar`

*For `bytes-read` and `bytes-written` the bytes represent the body of the request/response, so headers, etc are ignored.*

=== Http client metrics

Base name: `vertx.http.clients.@<id>`

Http client includes all the metrics of a [Http Server](#http-server-metrics) plus the following:

* `connections.max-pool-size` - A [Gauge](#gauge) of the max connection pool size
* `connections.pool-ratio` - A ratio [Gauge](#gauge) of the open connections / max connection pool size

=== Net server metrics

Base name: `vertx.net.servers.<host>:<port>`

* `open-connections` - A [Counter](#counter) of the number of open connections
* `open-connections.<remote-host>` - A [Counter](#counter) of the number of open connections for a particular remote host
* `connections` - A [Timer](#timer) of a connection and the rate of it's occurrence
* `exceptions` - A [Counter](#counter) of the number of exceptions
* `bytes-read` - A [Histogram](#histogram) of the number of bytes read.
* `bytes-written` - A [Histogram](#histogram) of the number of bytes written.

=== Net client metrics

Base name: `vertx.net.clients.@<id>`

Net client includes all the metrics of a [Net Server](#net-server-metrics)

=== Datagram socket metrics

Base name: `vertx.datagram`

* `sockets` - A [Counter](#counter) of the number of datagram sockets
* `exceptions` - A [Counter](#counter) of the number of exceptions
* `bytes-written` - A [Histogram](#histogram) of the number of bytes written.
* `<host>:<port>.bytes-read` - A [Histogram](#histogram) of the number of bytes read.
** This metric will only be available if the datagram socket is listening

[[jmx]]
== JMX

JMX is disabled by default.

If you want JMX, then you need to enabled that:

[source,groovy]
----
import io.vertx.groovy.core.Vertx
def vertx = Vertx.vertx([
  metricsOptions:[
    enabled:true,
    jmxEnabled:true
  ]
])

----

If running Vert.x from the command line you can enable metrics and JMX by uncommented the JMX_OPTS line in the
`vertx` or `vertx.bat` script:

----
JMX_OPTS="-Dcom.sun.management.jmxremote -Dvertx.options.jmxEnabled=true"
----

todo : add JMX domain configuration

== Enabling remote JMX

If you want the metrics to be exposed remotely over JMX, then you need to set, at minimum the following system property:

`com.sun.management.jmxremote`

If running from the command line this can be done by editing the `vertx` or `vertx.bat` and uncommenting the
`JMX_OPTS` line.

Please see the [Oracle JMX documentation](http://docs.oracle.com/javase/8/docs/technotes/guides/management/agent.html) for more information on configuring JMX

*If running Vert.x on a public server please be careful about exposing remote JMX access*

== Accessing Dropwizard Registry

todo